
[String]
result=执行结果
;主页
Init System=初始化系统
UnInit System=反初始化系统
system=系统
General=通用
DeviceTree=组织树
Preview=预览
DeviceFunction=云台
Playback=回放
Alarm=报警
TVWall=电视墙
DeviceManager=设备管理
ServiceStatus=服务状态
VirtualDisk=虚拟硬盘
AlarmHost=报警主机
Acess=门禁
VtCall=可视对讲
Test=测试
Prompt=提示
Error=错误
Init system success=初始化系统成功
Init system failed=初始化系统失败
Uninit system success=反初始化系统成功
Uninit system failed=反初始化系统失败
Yes=确定
;General
Server IP=登录IP：
Port=端口：
UserName=用户名：
Password=密码：
Login=登录
Logout=登出
Login Option=登录选项
HTTPS Mode=HTTPS 模式
doMain=域登录
Modify Password=修改密码
New Password=新密码
Client Info=客户端信息
Client Version=客户端版本
Client Road=客户端下载路径
Query Menu Right=查询菜单权限
Query FTP=查询FTP
Query Emap=查询Emap
Sync Time=校时
Handle Result=执行结果
Login success=登录成功
Login failed. error code %3D %1=登录失败。错误码 = %1
Logout success=登出成功
Get client version success, version %3D %1=获取版本号成功。版本号 = %1
Get client version failed, error code %3D %1=获取版本号失败。错误码 = %1
Get client road success, road %3D %1=获取客户端下载路径成功。路径 = %1
Get client road failed, error code %3D %1=获取客户端下载路径失败。错误码 = %1
Query e-map success. e-map server ip %3D %1, port %3D %2=查询FTP成功。服务ip = %1，端口 = %1
Query e-map failed, error code %3D %1= 查询FTP失败。错误码 = %1
Query menu right success. menu right count %3D %1 menuRights %3D=查询菜单权限成功。菜单权限数量 = %1, 菜单权限 = 
Query forbidden menu right success. menu right count %3D %1 menuRights %3D=查询禁止菜单权限成功。菜单权限数量 = %1, 菜单权限 = 
Query menu right failed. error code %3D %1=查询菜单权限失败。错误码 = %1
version=版本号
Modify password success=修改密码成功
Modify password failed. error code %3D %1=修改密码失败。错误码 = %1
Sync time success=校时成功
Sync time failed. error code %3D %1=校时失败。错误码 = %1
;Device
Query Organization Param=查询组织树参数
Org Code=组织编码
Query All Sub Code=查询所有子节点
Contain Device=包含设备
All Check=查询所有
Enc Channel=编码通道
Dec Channel=解码通道
AlarmIn Channel=报警输入通道
AlarmOut Channel=报警输出通道
TvWallIn Channel=大屏输入通道
TvWallOut Channel=大屏输出通道
Door Channel=门禁通道
Voice Channel=声音通道
Pos Channel=Pos 通道
RoadGate Channel=道闸通道
LED Channel=LED 通道
Virtual Channel=虚拟通道
Query Map Org=查询地图组织
Compress=压缩
Query Org=查询组织
User Data=用户数据
User Data Name=用户数据名称
User Data Info=用户数据信息
Get User Data=获取用户数据
Save User Data=保存用户数据
Del User Data=删除用户数据
Org=组织
Device=设备
Channel=通道
Get Device ByLayered failed. error code %3D %1=分级获取设备失败。错误码 = %1
Get Organization failed. error code %3D %1=获取组织失败。错误码 = %1
Get User Data success.=获取用户数据成功。
Get User Data Failed. error code %3D %1=获取用户数据失败。错误码 = %1
Save User Data success.=保存用户数据成功。
Save User Data Failed. error code %3D %1=保存用户数据失败。错误码 = %1
Del User Data success.=删除用户数据成功。
Del User Data Failed. error code %3D %1=删除用户数据失败。错误码 = %1
SetCompressType success.=设置压缩类型成功。
SetCompressType Failed. error code %3D %1=设置压缩类型失败。错误码 = %1
;Preview
;video
Video=视频
Picture=抓图
Sound=声音
Record=录像
Bayonet=卡口
VideoPlay=播放视频
SinglePlay=单播
VideoBaseParam=视频播放基本参数
ChannelCode=通道编码
IsDecode=是否硬解码
MulitviewPlay=多播
MulitviewParam=多播参数
ScreenNum=画面个数
TrackID=轨道ID
StartIndex=开始通道
StreamMode=播放模式
StreamMode=播放模式
DelayTime=延迟时间
GetStreamMode=获取播放模式
SetStreamMode=设置播放模式
StartVideo=开始播放
StopVideo=停止播放
Stop=关闭
DisplayRegion=显示区域
Top=顶
Bottom=底
Left=左
Right =右
Enable=允许
SetRegion=设置显示区域
LockVideo=锁定视频
UnlockVideo=解锁视频
Lock video success.=锁定视频成功
Lock video failed, error code %3D %1=锁定视频失败。错误码 = %1
Unlock video success.=解锁视频成功
Unlock video failed, error code %3D %1=解锁视频失败。错误码 = %1
Get Stream Mode success. uiStreamMode %3D %1=获取播放模式成功。播放模式 = %1
Get Stream Mode failed, iRet %3D %1=获取播放模式失败。错误码 = %1
Set Stream Mode success.=设置播放模式成功
Set Stream Mode failed, iRet %3D %1=设置播放模式失败。错误码 = %1
stop video success=停止播放成功
stop video failed, iRet %3D %1=停止播放失败。错误码 = %1
start video success=视频播放成功
start video failed, iRet %3D %1=视频播放失败。错误码 = %1
Get Picture Size success. lWidth %3D %1, lHeight %3D %2=获取图片大小成功。宽度 = %1，高度 = %2
Get Picture Size failed, iRet %3D %1= 获取图片大小失败。错误码 = %1
Get Picture To File success.=将图像存放到文件中成功。
Get Picture To File failed, iRet %3D %1=将图像存放到文件中失败。错误码 = %1
Get Picture To Buffer success. lBufSize %3D %1, iFactPicSize %3D %2=将图像数据放到缓冲地址成功。缓冲区大小 = %1，实际图像大小 = %2
Get Picture To File Buffer, iRet %3D %1=将图像数据放到缓冲地址失败。错误码 = %1
Set Display Region success.=设置显示区域成功
Set Display Region failed, iRet %3D %1=设置显示区域失败。错误码 = %1
;GetPicture
GetPicture=抓图
PicturePath=图片路径
GetPictureSize=获取图片大小
GetPictureToFile=抓图到文件
GetPictureToBuffer=抓图到缓存
Thumbnail=缩略图
;Sound
OpenSound=独占方式打开声音
CloseSound=关闭独占方式声音
Open Share Sound=共享方式打开声音
Close Share Sound=关闭共享方式声音
IsOpenSound=查询声音是否开启
SetVolume=设置音量
GetVolume=获取音量
Open Sound success.=独占方式打开声音成功
Open Sound failed, iRet %3D %1=独占方式打开声音失败。错误码 = %1
Close Sound success.=关闭独占方式声音成功
Close Sound failed, iRet %3D %1=关闭独占方式声音失败。错误码 = %1
Open Share Sound success.=共享方式打开声音成功
Open Share Sound failed, iRet %3D %1=共享方式打开声音失败。错误码 = %1
Close Share Sound success.=关闭共享方式声音成功
Close Share Sound failed, iRet %3D %1=关闭共享方式声音失败。错误码 = %1
Is Open Sound State success. bIsOpen %3D %1=声音开启状态判断成功。声音状态 = %1
Is Open Sound State failed, iRet %3D %1=声音开启状态判断失败。错误码 = %1
Set Volume success.=设置音量成功
Set Volume failed, iRet %3D %1=设置音量失败。错误码 = %1
Get Volume success. iVolume %3D %1=获取音量成功。音量值 = %1
Get Volume failed, iRet %3D %1=获取音量失败。错误码 = %1
;Record
RecordPath=录像路径
SplitLen=录像分割长度
SetSplitLen=设置录像分割长度
StartRecord=开始录像
StopRecord=停止录像
IsRecordState=判断是否正在录像
Set Split Record Len success.=设置录像分割长度成功
Set Split Record Len failed, iRet %3D %1=设置录像分割长度失败。错误码 = %1
Start Record success.=开始录像成功
Start Record failed, Please Enter The Record Path!=开始录像失败，请输入录像路径！
Start Record failed, iRet %3D %1=开始录像失败。错误码 = %1
Stop Record success.=停止录像成功
Stop Record failed, iRet %3D %1=停止录像失败。错误码 = %1
Get Is Record State success. bIsRecord %3D %1=判断是否正在录像成功。录像状态 = %1
Get Is Record State failed, iRet %3D %1=判断是否正在录像失败。错误码 = %1
;Bayonet
BayonetPictureParam=卡口图片监控参数
DeviceCode=设备编码
StreamType=码流类型
DataType=数据类型
GetBayDictionary=获取卡口图片字典
Language=语言
DictType=字典类型
GetBayDict=获取卡口图片字典
StartBayPic=开始卡口图片监控
StopBayPic=停止卡口图片监控
Start Bayonet Picture success.=开始卡口图片监控成功
Start Bayonet Picture failed, iRet %3D %1=开始卡口图片监控失败。错误码 = %1
Stop Bayonet Picture success.=停止卡口图片监控成功
Stop Bayonet Picture failed, iRet %3D %1=停止卡口图片监控失败。错误码 = %1
Get Bayonet Dictionary success.=获取卡口图片监控字典数据成功
Get Bayonet Dictionary failed, iRet %3D %1=获取卡口图片监控字典数据失败。错误码 = %1
;GB28181
Dest IP=目的 IP
Dest Port=目的端口
TransMode=传输类型
HeadType=头类型
TCPMode=连接方式
Device Code=设备编码
Default=0-默认连接方式
Active=1-主动连接方式
Passive=2-被动连接方式
;display
Brightness=亮度
Saturation=饱和度
Contrast=对比度
Hue=色调
GetColor=获取视频参数
SetColor=设置视频参数
SetIVSE=视频增强算法
DeHaze=去雾
Sensitivity=敏感度
Saturation=饱和度
DeNoise=去噪
LowLight=低照度增强
HDR=宽动态
WB=偏色校正
Number=支持增强的功能个数
StartIVSE=开启视频增强算法功能
StopIVSE=停止视频增强算法功能
Get Color success. iBrightness %3D %1, iContrast %3D %2, iSaturation %3D %3, iHue %3D %4=获取视频参数成功。亮度 = %1，对比度 = %2，饱和度 =%3，色调 = %4
Get Color failed, iRet %3D %1=获取视频参数失败。错误码 = %1
Set Color success.=设置视频参数成功
Set Color failed, iRet %3D %1=设置视频参数失败。错误码 = %1
Start IVSE success.=开启视频增强算法功能成功
Start IVSE failed, iRet %3D %1=开启视频增强算法功能失败。错误码 = %1
Stop IVSE success.=停止视频增强算法功能成功
Stop IVSE failed, iRet %3D %1=停止视频增强算法功能失败。错误码 = %1
;DeviceFunction
Function=功能控制
Camera=操作摄像头
Preset=预置点
Other=其他
Clear=清空数据
PtzOperateCamera=操作云台摄像头
OperateCamera=操作云台摄像头
CruiseID=巡航ID
Direct=方向
Command=命令
OperateType=操作类型
Step=步长
Extend=扩展数据
1-Increase=1-增加
2-Decrease=2-减小
0-Stop=0-停止
1-Open=1-开启
1-Variable=1-变倍
2-Zoom=2-变焦
3-Aperture=3-光圈
PtzOperateDirect=云台方向控制
OperateDirect=云台方向控制
StepX=水平步长
StepY=垂直步长
1-Upper=1-上
2-Under=2-下
3-Left=3-左
4-Right=4-右
5-Upper Left=5-左上
6-Under Left=6-左下
7-Upper Right=7-右上
8-Under Right=8-右下
PtzSitPosition=三维定位
PointX=水平坐标
PointY=垂直坐标
PointZ=变倍数
SitPosition=三维定位
MidX=中心点X
MidY=中心点Y
BoxWidth=候选框宽度
BoxHeight=候选框高度
WinWidth=窗口宽度
WinHeight=窗口高度
1-Zoom In=1-放大
2-Zoom Out=2-缩小
PtzOperatePresetPoint=控制预置点
PointCode=预置点编码
PointName=预置点名称
SeekTime=定位时间
PresetPoint=控制预置点
Get Preset=查询预置点
1-Location=1-定位
2-Set up=2-设置
3-Delete=3-删除
4-Update working time=4-更新工作时间
PtzOperateFocus=电动聚焦控制
0-Reset=0-重置
1-Continuous focusing=1-连续聚焦
2-Autofocusing=2-自动聚焦
Focus=焦距
Zoom=倍数
OperateFocus=电动聚焦控制
AlarmActionOut=报警输出控制
1-Status control=1-状态控制
2-Pattern control=2-模式控制
0-Close=0-关闭
1-Open/Automatically=1-开启/自动
2-Manual=2-手动
AlarmOut=报警输出控制
PtzOperateFunction=云台功能控制
0-Show_PtzMenu=0-显示云台菜单
1-Move_PtzMenu=1-控制云台菜单
2-Confirm_PtzMenuItem=2-确定云台菜单项
3-Set_LineScannBorder=3-设置线扫边界
4-Switch_LineScanBorder=4-开关线扫
5-Switch_AutoRotate=5-开关水平旋转
6-Switch_Light=6-开关灯光
7-Switch_RainBrush=7-开关雨刷器
8-Switch_InfraredLight=8-开关红外光
9-Switch_AssisentPoint=9-开关辅助点
10-Switch_Cruise=10-开关巡航功能
11-Switch_Track=11-开关巡迹
12-Switch_SetTrack=12-开关巡迹设置
CruiseId=巡航ID
TrackId=轨道ID
Switch=开关模式
BorderType=边界类型
16-Left boundary=16-左边界
17-Right boundary=17-右边界
AssisentType=辅助操作类型
23-Backlight compensation=23-背光补偿
24-Number doubled=24-数字变倍
27-Color turn black=27-彩转黑
35-Shutter time=35-快门时间
41-Brightness=41-亮度
42-Image flip=42-图像翻转
43-Hidding preset point's name=43-隐藏预置点名称
80-Restore factory settings=80-恢复出厂设置
MoveType=移动类型
25-Upward movement=25-上移
26-Move down=26-下移
27-Left shift=27-左移
28-Right shift=28-右移
SwitchMenu=云台菜单
22-Open the platform menu=22-打开云台菜单
23-Close the platform menu=23-关闭云台菜单
OperateFunction=云台功能操作
PtzArrangePtz=云台协商
ArrangePtz=云台协商
LockTime=锁定时间
0-Unknow=0-未知
1-Lock current camera=1-锁定当前摄像头
2-Unlock current camera=2-解锁当前摄像头
3-Unlock all camera=3-解锁所有摄像头
4-Lock all camera=4-锁定所有的摄像头
5-Query lock status=5-查询锁定状态
PtzOperateCamera failed. error code %3D %1=操作云台摄像头失败。错误码 = %1
PtzOperateCamera Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=操作云台摄像头成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzOperateDirect Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=云台方向控制成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzOperateDirect failed. error code %3D %1=云台方向控制失败。错误码 = %1
PtzOperatePresetPoint Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=控制预置点成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzOperatePresetPoint failed. error code %3D %1=控制预置点失败。错误码 = %1
PtzGetPresetPoints failed. error code %3D %1=查询预置点失败。错误码 = %1
PtzGetPresetPoints success.=查询预置成功
PtzSitPositionEx Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=三维定位成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzSitPositionEx failed. error code %3D %1=三维定位失败。错误码 = %1
PtzSitPosition Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=三维定位成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzSitPosition failed. error code %3D %1=三维定位失败。错误码 = %1
PtzOperateFocus Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=电动聚焦控制成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzOperateFocus failed. error code %3D %1=电动聚焦控制失败。错误码 = %1
AlarmActionOut Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=报警输出控制成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
AlarmActionOut failed. error code %3D %1=报警输出控制失败。错误码 = %1
PtzArrangePtz success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=云台协商成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3
PtzArrangePtz failed. error code %3D %1=云台协商失败。错误码 = %1
PtzOperateFunction Success. iResult%3D%1 LockUserName%3D%2 LockUserLevel%3D%3.=云台功能操作成功。操作结果 = %1，锁定云台的用户名称 = %2，锁定云台的用户级别 = %3。
PtzOperateFunction failed. error code %3D %1=云台功能操作失败。错误码 = %1
;Playback
Record=录像
Playback=回放
Download=下载
Sound=声音
Picture=抓图
StartTime=开始时间
EndTime=结束时间
Device ID=设备ID
SourceType=录像源类型
StreamType=码流类型
RecordType=录像类型
1-Main stream=1-主码流
2-Auxiliary code stream=2-辅码流
1-All=1-全部
2-Device record=2-设备录像
3-Center=3-平台录像
0-All=0-全部
1-Manual=1-手动录像
2-Alarm record=2-报警录像
0-Time-ChannelID=0-时间+通道ID
1-Time-ChannelName=1-时间+通道名称
2-ChannelID-Time=2-通道ID+时间
3-ChannelName-Time=3-通道名称+时间
Query=查询
Query Record=查询录像
QueryRecordDate=查询录像日期
Lock=锁定
User ID=用户ID
IsForce=是否强制
LockRecordFile=锁定录像文件
UnlockRecordFile=解锁录像文件
QueryLockRecord=查询录像锁定信息
Duration=录像时长
StartRemoteRecord=开启手动录像
StopRemoteRecord=停止手动录像
Seq=序号
FileName=文件名称
FileSize=文件大小
StreamType=码流类型
bLock=是否被锁定
Speed=速度
Direction=方向
Play=播放
Start by Time=按时间播放
Start by File=按文件播放
Pause=暂停
Frame Step=单帧播放
Set Speed=设置速度
Seek=定位
0-Forward Direction=0-正放
1-Back Direction=1-倒放
Back=倒放
Forward=正放
DownLoad=下载
Download By File=按文件下载
Download By Time=按时间下载
Resume=恢复
GetRecordInfo=获取录像下载信息
SplitSize=分割文件大小
DownLoadFileName=下载文件名称
DownLoadPath=下载路径
ChannelName=通道名称
DiskID=磁盘ID
FileFormat=下载文件格式
NameRule=命名规则
RecordType=录像类型
PicFormat=图片格式
Path=文件路径
Picture=抓图
GetPictureBuf=抓图到缓存
Get24BitPictureFile=抓图到文件
ConvertToJpegFile=图片数据转换为jpeg
ConvertToBmpFile=图片数据转换为bmp
Width=图像宽度
Height=图像高度
Quality=图片压缩质量
Size=图像数据大小
Type=图像类型
GetRecordStatus=查询通道录像信息
GetPlayedTime=获取当前播放时间
GetProviderType=获取码流厂商类型
Please query the record first=请先查询录像
Query Record Date success, RecordDays %3D=查询录像日期成功。录像日期 =
Query Record Date failed, iRet %3D %1=查询录像日期失败。错误码 = %1
lock record file success=锁定录像文件成功
lock record file fail=锁定录像文件失败
unlock record file success=解锁录像文件成功
unlock record file fail=解锁录像文件失败
Query Lock Record success, iRetCount %3D %1=查询录像锁定信息成功。返回个数 = %1
Query Lock Record failed, iRet %3D %1=查询录像锁定信息失败。错误码 = %1
Start Remote Record success.=开启手动录像成功
Start Remote Record failed, iRet %3D %1=开启手动录像失败。错误码 = %1
Stop Remote Record success.=停止手动录像成功
Stop Remote Record failed, iRet %3D %1=停止手动录像失败。错误码 = %1
stop playback success=停止播放成功
stop playback failed, iRet %3D %1=停止播放失败。错误码 = %1
start playback by time success=按时间播放成功
start playback by time failed, iRet %3D %1=按时间播放失败。错误码 = %1
Pause Playback success=暂停播放成功
Pause Playback failed, iRet %3D %1=暂停播放失败。错误码 = %1
Resume Playback success=重播成功
Resume Playback failed, iRet %3D %1=重播失败。错误码 = %1
Playback Frame Step success=单帧播放成功
Playback Frame Step failed, iRet %3D %1=单帧播放失败。错误码 = %1
Set Playback Speed success.=设置播放速率成功
Set Playback Speed failed, iRet %3D %1=设置播放速率失败。错误码 = %1
Playback Seek success.=定位成功
Playback Seek failed, iRet %3D %1=定位失败。错误码 = %1
Playback Back success.=倒放成功
Playback Back failed, iRet %3D %1=倒放失败。错误码 = %1
StopDownloadRecord success=停止下载成功
StopDownloadRecord failed, iRet = %1=停止下载失败。错误码 = %1
StartDownloadRecordByTime success=按时间下载成功
StartDownloadRecordByTime failed, iRet %3D %1=按时间下载失败。错误码 = %1
PauseDownloadRecord success=暂停下载成功
PauseDownloadRecord failed, iRet %3D %1=暂停下载失败。错误码 = %1
ResumeDownloadRecord success=重新下载成功
ResumeDownloadRecord failed, iRet %3D %1=重新下载失败。错误码 = %1
Get Download Record Info success. FileCount %3D %1, DownloadStatus %3D %2, DownloadMode %3D %3=获取录像下载信息成功。文件数量 = %1，下载状态 = %2，下载模式 = %3
Get Download Record Info failed, iRet %3D %1=获取录像下载信息失败。错误码 = %1
Get Picture To Buffer success. lBufSize %3D %1, iFactPicSize %3D %2=将图片存放到图像数据的缓存地址中成功。缓存区大小 = %1，图片数据大小 = %2
Get Picture To File Buffer, iRet %3D %1=将图片存放到图像数据的缓存地址中失败。错误码 = %1
Get24Bit Picture File success=将图片放到文件中成功
Get24Bit Picture File failed, iRet %3D %1=将图片放到文件中失败。错误码 = %1
Convert To Jpeg File success.=将图片数据转为Jpeg成功
Convert To Jpeg File failed, iRet %3D %1=将图片数据转为Jpeg失败。错误码 = %1
Convert To Bmp File success.=将图片数据转为Bmp成功
Convert To Bmp File failed, iRet %3D %1=将图片数据转为Bmp失败。错误码 = %1
Get Record Status success=查询通道录像信息成功
Get Record Status failed, iRet %3D %1=查询通道录像信息失败。错误码 = %1
GetPlayedTime success, tTime %3D %1=获取当前播放时间成功。时间 = %1
GetPlayedTime failed, iRet %3D %1=获取当前播放时间失败。错误码 = %1
GetProviderType success, iProviderType %3D %1=获取码流厂商类型成功。厂商类型 = %1
GetProviderType failed, iRet %3D %1=获取码流厂商类型失败。错误码 = %1
;Alarm
Export=导出
Alarm Options=报警
AlarmBeginTime=报警开始时间
AlarmEndTime=报警结束时间
OrgCode=组织编码
AlarmId=报警ID
AlarmCode=报警编码
AlarmGradeList=报警等级
AlarmTypeList=报警类型
AlarmStatusList=报警状态
PageSize=分页大小
PageNum=页面编号
Handle Options=处理
HandleBeginTime=处理开始时间
HandleEndTime=处理结束时间
QueryType=查询类型
HandleStatusList=处理状态
HandleStatus=处理状态
HandleUser=报警处理人
HandleMsg=处理意见
EmailList=邮箱列表
AlarmProcessFlow=报警处理流程
AlarmBlock=屏蔽报警
AlarmType=报警类型
AlarmSourceCode=报警源编码
Duration(s)=有效时长（秒）
Untreated Alarm=未处理
Have to deal with alarm=已处理
Sort Options=排序
SortOrder=排序方向
SortType=排序类型
1-Alarm time=1-报警时间
2-Alarm type=2-报警类型
3-Alarm level=3-报警等级
4-HandleUser=4-处理人
5-Processing state=5-处理状态
0-Ascending order=0-升序
1-Descending order=1-降序
AlarmQuery=报警查询
AlarmTypeQuery=报警类型查询
AlarmCountQuery=报警数量查询
Shielded push=屏蔽推送
Stop refresh=停止刷新
AlarmExport=报警导出
AlarmQuery Success.=报警查询成功
AlarmQuery failed. error code %3D %1=报警查询失败。错误码 = %1
GetAlarmType Success.=报警类型查询成功
GetAlarmType failed. error code %3D %1=报警类型查询失败。错误码 = %1
QueryAlarmCount Success,alarm count%3D%1.=报警数量查询成功，报警个数=%1
QueryAlarmCount failed. error code %3D %1=报警数量查询失败。错误码 = %1
AlarmExport Success.=报警导出成功
AlarmExport failed. error code %3D %1=报警导出失败。错误码 = %1
AlarmEventNotify.=报警事件通知
AlarmConfirmNotify.=报警确认通知
AlarmPictureNotify.=报警图片通知
AlarmExportNotify.=报警输出通知
AlarmQueryPF Success.=查询报警处理流程成功
AlarmQueryPF failed. error code %3D %1=查询报警处理流程失败。错误码 = %1
Wnd=窗口
Smart Wnd=智能窗口
Split=分割
Custom Split=自定义分割
PopupMenu=弹出菜单
Bmp path=BMP路径
Text=文本
Handle=操作
Add=增加
Del=删除
Set Window Text=设置窗口文本
Set window text success.=设置窗口文本成功
Set window text failed, error code %3D %1=设置窗口文本失败。错误码 = %1
Logout failed. error code %3D %1=登出失败。错误码 = %1
SplitSmartWnd success=分割窗口成功
SplitSmartWnd failed. error code %3D %1=分割窗口失败。错误码 = %1
CustomSplitSmartWnd success=自定义分割窗口成功
CustomSplitSmartWnd failed. error code %3D %1=自定义分割窗口失败。错误码 = %1
AppendPopupMenu failed. error code %3D %1=添加弹出菜单失败。错误码 = %1
EnablePopupMenu success=允许弹出菜单成功
EnablePopupMenu failed. error code %3D %1=允许弹出菜单失败。错误码 = %1
DeletePopupMenu failed. error code %3D %1=删除弹出菜单失败。错误码 = %1
Get Device Failed. error code %3D %1=获取设备失败。错误码 = %1
Query Record success, RecordCount %3D %1=查询录像成功。录像数 = %1
Query Record failed, iRet %3D %1=查询录像失败。错误码 = %1
AlarmConfirm=报警确认
1-In the process of processing=1-处理中
2-Resolved=2-已处理
3-False positives=3-误报
4-Ignore=4-忽略
5-Unsolved=5-未处理
AlarmConfirm failed. error code %3D %1=报警确认失败。错误码 = %1
AlarmConfirm Success.=报警确认成功
Please input correct params!=请输入正确参数！
AlarmBlock Success.=屏蔽报警成功
AlarmBlock failed. error code %3D %1=屏蔽报警失败。错误码 = %1







