
[Menus]
DeviceFunction=1
Playback=1
Alarm=1
TVWall=0
DeviceManager=0
ServiceStatus=0
VirtualDisk=0
AlarmHost=0
Acess=0
VtCall=0
Test=0

[Language]
Name=English
Type=1

#0:VSL 1:EXPRESS OR PRO
[PlatFormType]
Type=1
